version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: team
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: team
      MYSQL_USER: team
      MYSQL_PASSWORD: team
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: