// Code generated by ent, DO NOT EDIT.

package transientmember

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the transientmember type in the database.
	Label = "transient_member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTransientMemberID holds the string denoting the transient_member_id field in the database.
	FieldTransientMemberID = "transient_member_id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPicture holds the string denoting the picture field in the database.
	FieldPicture = "picture"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// Table holds the table name of the transientmember in the database.
	Table = "transient_members"
)

// Columns holds all SQL columns for transientmember fields.
var Columns = []string{
	FieldID,
	FieldTransientMemberID,
	FieldEmail,
	FieldPicture,
	FieldNickname,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the TransientMember queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTransientMemberID orders the results by the transient_member_id field.
func ByTransientMemberID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransientMemberID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPicture orders the results by the picture field.
func ByPicture(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPicture, opts...).ToFunc()
}

// ByNickname orders the results by the nickname field.
func ByNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNickname, opts...).ToFunc()
}
