// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnnouncementsColumns holds the columns for the "announcements" table.
	AnnouncementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
	}
	// AnnouncementsTable holds the schema information for the "announcements" table.
	AnnouncementsTable = &schema.Table{
		Name:       "announcements",
		Columns:    AnnouncementsColumns,
		PrimaryKey: []*schema.Column{AnnouncementsColumns[0]},
	}
	// MembersColumns holds the columns for the "members" table.
	MembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "member_id", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "picture", Type: field.TypeString},
		{Name: "nickname", Type: field.TypeString},
		{Name: "bio", Type: field.TypeString, Size: 2147483647},
		{Name: "preferred_role", Type: field.TypeString},
		{Name: "team_members", Type: field.TypeInt, Nullable: true},
	}
	// MembersTable holds the schema information for the "members" table.
	MembersTable = &schema.Table{
		Name:       "members",
		Columns:    MembersColumns,
		PrimaryKey: []*schema.Column{MembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "members_teams_members",
				Columns:    []*schema.Column{MembersColumns[7]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PositionsColumns holds the columns for the "positions" table.
	PositionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "role", Type: field.TypeString},
		{Name: "vacancy", Type: field.TypeInt8},
		{Name: "team_id", Type: field.TypeInt, Nullable: true},
	}
	// PositionsTable holds the schema information for the "positions" table.
	PositionsTable = &schema.Table{
		Name:       "positions",
		Columns:    PositionsColumns,
		PrimaryKey: []*schema.Column{PositionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "positions_teams_positions",
				Columns:    []*schema.Column{PositionsColumns[3]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SkillsColumns holds the columns for the "skills" table.
	SkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// SkillsTable holds the schema information for the "skills" table.
	SkillsTable = &schema.Table{
		Name:       "skills",
		Columns:    SkillsColumns,
		PrimaryKey: []*schema.Column{SkillsColumns[0]},
	}
	// TeamsColumns holds the columns for the "teams" table.
	TeamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "headcount", Type: field.TypeInt8},
	}
	// TeamsTable holds the schema information for the "teams" table.
	TeamsTable = &schema.Table{
		Name:       "teams",
		Columns:    TeamsColumns,
		PrimaryKey: []*schema.Column{TeamsColumns[0]},
	}
	// TransientMembersColumns holds the columns for the "transient_members" table.
	TransientMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "transient_member_id", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "picture", Type: field.TypeString},
		{Name: "nickname", Type: field.TypeString},
	}
	// TransientMembersTable holds the schema information for the "transient_members" table.
	TransientMembersTable = &schema.Table{
		Name:       "transient_members",
		Columns:    TransientMembersColumns,
		PrimaryKey: []*schema.Column{TransientMembersColumns[0]},
	}
	// SkillUsersColumns holds the columns for the "skill_users" table.
	SkillUsersColumns = []*schema.Column{
		{Name: "skill_id", Type: field.TypeInt},
		{Name: "member_id", Type: field.TypeInt},
	}
	// SkillUsersTable holds the schema information for the "skill_users" table.
	SkillUsersTable = &schema.Table{
		Name:       "skill_users",
		Columns:    SkillUsersColumns,
		PrimaryKey: []*schema.Column{SkillUsersColumns[0], SkillUsersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "skill_users_skill_id",
				Columns:    []*schema.Column{SkillUsersColumns[0]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "skill_users_member_id",
				Columns:    []*schema.Column{SkillUsersColumns[1]},
				RefColumns: []*schema.Column{MembersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// SkillTeamsColumns holds the columns for the "skill_teams" table.
	SkillTeamsColumns = []*schema.Column{
		{Name: "skill_id", Type: field.TypeInt},
		{Name: "team_id", Type: field.TypeInt},
	}
	// SkillTeamsTable holds the schema information for the "skill_teams" table.
	SkillTeamsTable = &schema.Table{
		Name:       "skill_teams",
		Columns:    SkillTeamsColumns,
		PrimaryKey: []*schema.Column{SkillTeamsColumns[0], SkillTeamsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "skill_teams_skill_id",
				Columns:    []*schema.Column{SkillTeamsColumns[0]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "skill_teams_team_id",
				Columns:    []*schema.Column{SkillTeamsColumns[1]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnnouncementsTable,
		MembersTable,
		PositionsTable,
		SkillsTable,
		TeamsTable,
		TransientMembersTable,
		SkillUsersTable,
		SkillTeamsTable,
	}
)

func init() {
	MembersTable.ForeignKeys[0].RefTable = TeamsTable
	PositionsTable.ForeignKeys[0].RefTable = TeamsTable
	SkillUsersTable.ForeignKeys[0].RefTable = SkillsTable
	SkillUsersTable.ForeignKeys[1].RefTable = MembersTable
	SkillTeamsTable.ForeignKeys[0].RefTable = SkillsTable
	SkillTeamsTable.ForeignKeys[1].RefTable = TeamsTable
}
