// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend_golang/ent/member"
	"backend_golang/ent/predicate"
	"backend_golang/ent/skill"
	"backend_golang/ent/team"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemberUpdate is the builder for updating Member entities.
type MemberUpdate struct {
	config
	hooks    []Hook
	mutation *MemberMutation
}

// Where appends a list predicates to the MemberUpdate builder.
func (mu *MemberUpdate) Where(ps ...predicate.Member) *MemberUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetMemberID sets the "member_id" field.
func (mu *MemberUpdate) SetMemberID(s string) *MemberUpdate {
	mu.mutation.SetMemberID(s)
	return mu
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (mu *MemberUpdate) SetNillableMemberID(s *string) *MemberUpdate {
	if s != nil {
		mu.SetMemberID(*s)
	}
	return mu
}

// SetEmail sets the "email" field.
func (mu *MemberUpdate) SetEmail(s string) *MemberUpdate {
	mu.mutation.SetEmail(s)
	return mu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (mu *MemberUpdate) SetNillableEmail(s *string) *MemberUpdate {
	if s != nil {
		mu.SetEmail(*s)
	}
	return mu
}

// SetPicture sets the "picture" field.
func (mu *MemberUpdate) SetPicture(s string) *MemberUpdate {
	mu.mutation.SetPicture(s)
	return mu
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (mu *MemberUpdate) SetNillablePicture(s *string) *MemberUpdate {
	if s != nil {
		mu.SetPicture(*s)
	}
	return mu
}

// SetNickname sets the "nickname" field.
func (mu *MemberUpdate) SetNickname(s string) *MemberUpdate {
	mu.mutation.SetNickname(s)
	return mu
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (mu *MemberUpdate) SetNillableNickname(s *string) *MemberUpdate {
	if s != nil {
		mu.SetNickname(*s)
	}
	return mu
}

// SetBio sets the "bio" field.
func (mu *MemberUpdate) SetBio(s string) *MemberUpdate {
	mu.mutation.SetBio(s)
	return mu
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (mu *MemberUpdate) SetNillableBio(s *string) *MemberUpdate {
	if s != nil {
		mu.SetBio(*s)
	}
	return mu
}

// SetPreferredRole sets the "preferred_role" field.
func (mu *MemberUpdate) SetPreferredRole(s string) *MemberUpdate {
	mu.mutation.SetPreferredRole(s)
	return mu
}

// SetNillablePreferredRole sets the "preferred_role" field if the given value is not nil.
func (mu *MemberUpdate) SetNillablePreferredRole(s *string) *MemberUpdate {
	if s != nil {
		mu.SetPreferredRole(*s)
	}
	return mu
}

// AddSkillIDs adds the "skills" edge to the Skill entity by IDs.
func (mu *MemberUpdate) AddSkillIDs(ids ...int) *MemberUpdate {
	mu.mutation.AddSkillIDs(ids...)
	return mu
}

// AddSkills adds the "skills" edges to the Skill entity.
func (mu *MemberUpdate) AddSkills(s ...*Skill) *MemberUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return mu.AddSkillIDs(ids...)
}

// SetTeamsID sets the "teams" edge to the Team entity by ID.
func (mu *MemberUpdate) SetTeamsID(id int) *MemberUpdate {
	mu.mutation.SetTeamsID(id)
	return mu
}

// SetNillableTeamsID sets the "teams" edge to the Team entity by ID if the given value is not nil.
func (mu *MemberUpdate) SetNillableTeamsID(id *int) *MemberUpdate {
	if id != nil {
		mu = mu.SetTeamsID(*id)
	}
	return mu
}

// SetTeams sets the "teams" edge to the Team entity.
func (mu *MemberUpdate) SetTeams(t *Team) *MemberUpdate {
	return mu.SetTeamsID(t.ID)
}

// Mutation returns the MemberMutation object of the builder.
func (mu *MemberUpdate) Mutation() *MemberMutation {
	return mu.mutation
}

// ClearSkills clears all "skills" edges to the Skill entity.
func (mu *MemberUpdate) ClearSkills() *MemberUpdate {
	mu.mutation.ClearSkills()
	return mu
}

// RemoveSkillIDs removes the "skills" edge to Skill entities by IDs.
func (mu *MemberUpdate) RemoveSkillIDs(ids ...int) *MemberUpdate {
	mu.mutation.RemoveSkillIDs(ids...)
	return mu
}

// RemoveSkills removes "skills" edges to Skill entities.
func (mu *MemberUpdate) RemoveSkills(s ...*Skill) *MemberUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return mu.RemoveSkillIDs(ids...)
}

// ClearTeams clears the "teams" edge to the Team entity.
func (mu *MemberUpdate) ClearTeams() *MemberUpdate {
	mu.mutation.ClearTeams()
	return mu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MemberUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MemberUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MemberUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MemberUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(member.Table, member.Columns, sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.MemberID(); ok {
		_spec.SetField(member.FieldMemberID, field.TypeString, value)
	}
	if value, ok := mu.mutation.Email(); ok {
		_spec.SetField(member.FieldEmail, field.TypeString, value)
	}
	if value, ok := mu.mutation.Picture(); ok {
		_spec.SetField(member.FieldPicture, field.TypeString, value)
	}
	if value, ok := mu.mutation.Nickname(); ok {
		_spec.SetField(member.FieldNickname, field.TypeString, value)
	}
	if value, ok := mu.mutation.Bio(); ok {
		_spec.SetField(member.FieldBio, field.TypeString, value)
	}
	if value, ok := mu.mutation.PreferredRole(); ok {
		_spec.SetField(member.FieldPreferredRole, field.TypeString, value)
	}
	if mu.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   member.SkillsTable,
			Columns: member.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedSkillsIDs(); len(nodes) > 0 && !mu.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   member.SkillsTable,
			Columns: member.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   member.SkillsTable,
			Columns: member.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.TeamsTable,
			Columns: []string{member.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.TeamsTable,
			Columns: []string{member.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MemberUpdateOne is the builder for updating a single Member entity.
type MemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberMutation
}

// SetMemberID sets the "member_id" field.
func (muo *MemberUpdateOne) SetMemberID(s string) *MemberUpdateOne {
	muo.mutation.SetMemberID(s)
	return muo
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (muo *MemberUpdateOne) SetNillableMemberID(s *string) *MemberUpdateOne {
	if s != nil {
		muo.SetMemberID(*s)
	}
	return muo
}

// SetEmail sets the "email" field.
func (muo *MemberUpdateOne) SetEmail(s string) *MemberUpdateOne {
	muo.mutation.SetEmail(s)
	return muo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (muo *MemberUpdateOne) SetNillableEmail(s *string) *MemberUpdateOne {
	if s != nil {
		muo.SetEmail(*s)
	}
	return muo
}

// SetPicture sets the "picture" field.
func (muo *MemberUpdateOne) SetPicture(s string) *MemberUpdateOne {
	muo.mutation.SetPicture(s)
	return muo
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (muo *MemberUpdateOne) SetNillablePicture(s *string) *MemberUpdateOne {
	if s != nil {
		muo.SetPicture(*s)
	}
	return muo
}

// SetNickname sets the "nickname" field.
func (muo *MemberUpdateOne) SetNickname(s string) *MemberUpdateOne {
	muo.mutation.SetNickname(s)
	return muo
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (muo *MemberUpdateOne) SetNillableNickname(s *string) *MemberUpdateOne {
	if s != nil {
		muo.SetNickname(*s)
	}
	return muo
}

// SetBio sets the "bio" field.
func (muo *MemberUpdateOne) SetBio(s string) *MemberUpdateOne {
	muo.mutation.SetBio(s)
	return muo
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (muo *MemberUpdateOne) SetNillableBio(s *string) *MemberUpdateOne {
	if s != nil {
		muo.SetBio(*s)
	}
	return muo
}

// SetPreferredRole sets the "preferred_role" field.
func (muo *MemberUpdateOne) SetPreferredRole(s string) *MemberUpdateOne {
	muo.mutation.SetPreferredRole(s)
	return muo
}

// SetNillablePreferredRole sets the "preferred_role" field if the given value is not nil.
func (muo *MemberUpdateOne) SetNillablePreferredRole(s *string) *MemberUpdateOne {
	if s != nil {
		muo.SetPreferredRole(*s)
	}
	return muo
}

// AddSkillIDs adds the "skills" edge to the Skill entity by IDs.
func (muo *MemberUpdateOne) AddSkillIDs(ids ...int) *MemberUpdateOne {
	muo.mutation.AddSkillIDs(ids...)
	return muo
}

// AddSkills adds the "skills" edges to the Skill entity.
func (muo *MemberUpdateOne) AddSkills(s ...*Skill) *MemberUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return muo.AddSkillIDs(ids...)
}

// SetTeamsID sets the "teams" edge to the Team entity by ID.
func (muo *MemberUpdateOne) SetTeamsID(id int) *MemberUpdateOne {
	muo.mutation.SetTeamsID(id)
	return muo
}

// SetNillableTeamsID sets the "teams" edge to the Team entity by ID if the given value is not nil.
func (muo *MemberUpdateOne) SetNillableTeamsID(id *int) *MemberUpdateOne {
	if id != nil {
		muo = muo.SetTeamsID(*id)
	}
	return muo
}

// SetTeams sets the "teams" edge to the Team entity.
func (muo *MemberUpdateOne) SetTeams(t *Team) *MemberUpdateOne {
	return muo.SetTeamsID(t.ID)
}

// Mutation returns the MemberMutation object of the builder.
func (muo *MemberUpdateOne) Mutation() *MemberMutation {
	return muo.mutation
}

// ClearSkills clears all "skills" edges to the Skill entity.
func (muo *MemberUpdateOne) ClearSkills() *MemberUpdateOne {
	muo.mutation.ClearSkills()
	return muo
}

// RemoveSkillIDs removes the "skills" edge to Skill entities by IDs.
func (muo *MemberUpdateOne) RemoveSkillIDs(ids ...int) *MemberUpdateOne {
	muo.mutation.RemoveSkillIDs(ids...)
	return muo
}

// RemoveSkills removes "skills" edges to Skill entities.
func (muo *MemberUpdateOne) RemoveSkills(s ...*Skill) *MemberUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return muo.RemoveSkillIDs(ids...)
}

// ClearTeams clears the "teams" edge to the Team entity.
func (muo *MemberUpdateOne) ClearTeams() *MemberUpdateOne {
	muo.mutation.ClearTeams()
	return muo
}

// Where appends a list predicates to the MemberUpdate builder.
func (muo *MemberUpdateOne) Where(ps ...predicate.Member) *MemberUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MemberUpdateOne) Select(field string, fields ...string) *MemberUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Member entity.
func (muo *MemberUpdateOne) Save(ctx context.Context) (*Member, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MemberUpdateOne) SaveX(ctx context.Context) *Member {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MemberUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MemberUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MemberUpdateOne) sqlSave(ctx context.Context) (_node *Member, err error) {
	_spec := sqlgraph.NewUpdateSpec(member.Table, member.Columns, sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Member.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, member.FieldID)
		for _, f := range fields {
			if !member.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != member.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.MemberID(); ok {
		_spec.SetField(member.FieldMemberID, field.TypeString, value)
	}
	if value, ok := muo.mutation.Email(); ok {
		_spec.SetField(member.FieldEmail, field.TypeString, value)
	}
	if value, ok := muo.mutation.Picture(); ok {
		_spec.SetField(member.FieldPicture, field.TypeString, value)
	}
	if value, ok := muo.mutation.Nickname(); ok {
		_spec.SetField(member.FieldNickname, field.TypeString, value)
	}
	if value, ok := muo.mutation.Bio(); ok {
		_spec.SetField(member.FieldBio, field.TypeString, value)
	}
	if value, ok := muo.mutation.PreferredRole(); ok {
		_spec.SetField(member.FieldPreferredRole, field.TypeString, value)
	}
	if muo.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   member.SkillsTable,
			Columns: member.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedSkillsIDs(); len(nodes) > 0 && !muo.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   member.SkillsTable,
			Columns: member.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   member.SkillsTable,
			Columns: member.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.TeamsTable,
			Columns: []string{member.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.TeamsTable,
			Columns: []string{member.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Member{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
