// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend_golang/ent/member"
	"backend_golang/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemberUpdate is the builder for updating Member entities.
type MemberUpdate struct {
	config
	hooks    []Hook
	mutation *MemberMutation
}

// Where appends a list predicates to the MemberUpdate builder.
func (mu *MemberUpdate) Where(ps ...predicate.Member) *MemberUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetMemberID sets the "member_id" field.
func (mu *MemberUpdate) SetMemberID(i int64) *MemberUpdate {
	mu.mutation.ResetMemberID()
	mu.mutation.SetMemberID(i)
	return mu
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (mu *MemberUpdate) SetNillableMemberID(i *int64) *MemberUpdate {
	if i != nil {
		mu.SetMemberID(*i)
	}
	return mu
}

// AddMemberID adds i to the "member_id" field.
func (mu *MemberUpdate) AddMemberID(i int64) *MemberUpdate {
	mu.mutation.AddMemberID(i)
	return mu
}

// SetName sets the "name" field.
func (mu *MemberUpdate) SetName(s string) *MemberUpdate {
	mu.mutation.SetName(s)
	return mu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (mu *MemberUpdate) SetNillableName(s *string) *MemberUpdate {
	if s != nil {
		mu.SetName(*s)
	}
	return mu
}

// SetDescription sets the "description" field.
func (mu *MemberUpdate) SetDescription(s string) *MemberUpdate {
	mu.mutation.SetDescription(s)
	return mu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (mu *MemberUpdate) SetNillableDescription(s *string) *MemberUpdate {
	if s != nil {
		mu.SetDescription(*s)
	}
	return mu
}

// SetHeadacount sets the "headacount" field.
func (mu *MemberUpdate) SetHeadacount(i int8) *MemberUpdate {
	mu.mutation.ResetHeadacount()
	mu.mutation.SetHeadacount(i)
	return mu
}

// SetNillableHeadacount sets the "headacount" field if the given value is not nil.
func (mu *MemberUpdate) SetNillableHeadacount(i *int8) *MemberUpdate {
	if i != nil {
		mu.SetHeadacount(*i)
	}
	return mu
}

// AddHeadacount adds i to the "headacount" field.
func (mu *MemberUpdate) AddHeadacount(i int8) *MemberUpdate {
	mu.mutation.AddHeadacount(i)
	return mu
}

// Mutation returns the MemberMutation object of the builder.
func (mu *MemberUpdate) Mutation() *MemberMutation {
	return mu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MemberUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MemberUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MemberUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MemberUpdate) check() error {
	if v, ok := mu.mutation.MemberID(); ok {
		if err := member.MemberIDValidator(v); err != nil {
			return &ValidationError{Name: "member_id", err: fmt.Errorf(`ent: validator failed for field "Member.member_id": %w`, err)}
		}
	}
	return nil
}

func (mu *MemberUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(member.Table, member.Columns, sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.MemberID(); ok {
		_spec.SetField(member.FieldMemberID, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.AddedMemberID(); ok {
		_spec.AddField(member.FieldMemberID, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.Name(); ok {
		_spec.SetField(member.FieldName, field.TypeString, value)
	}
	if value, ok := mu.mutation.Description(); ok {
		_spec.SetField(member.FieldDescription, field.TypeString, value)
	}
	if value, ok := mu.mutation.Headacount(); ok {
		_spec.SetField(member.FieldHeadacount, field.TypeInt8, value)
	}
	if value, ok := mu.mutation.AddedHeadacount(); ok {
		_spec.AddField(member.FieldHeadacount, field.TypeInt8, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MemberUpdateOne is the builder for updating a single Member entity.
type MemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberMutation
}

// SetMemberID sets the "member_id" field.
func (muo *MemberUpdateOne) SetMemberID(i int64) *MemberUpdateOne {
	muo.mutation.ResetMemberID()
	muo.mutation.SetMemberID(i)
	return muo
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (muo *MemberUpdateOne) SetNillableMemberID(i *int64) *MemberUpdateOne {
	if i != nil {
		muo.SetMemberID(*i)
	}
	return muo
}

// AddMemberID adds i to the "member_id" field.
func (muo *MemberUpdateOne) AddMemberID(i int64) *MemberUpdateOne {
	muo.mutation.AddMemberID(i)
	return muo
}

// SetName sets the "name" field.
func (muo *MemberUpdateOne) SetName(s string) *MemberUpdateOne {
	muo.mutation.SetName(s)
	return muo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (muo *MemberUpdateOne) SetNillableName(s *string) *MemberUpdateOne {
	if s != nil {
		muo.SetName(*s)
	}
	return muo
}

// SetDescription sets the "description" field.
func (muo *MemberUpdateOne) SetDescription(s string) *MemberUpdateOne {
	muo.mutation.SetDescription(s)
	return muo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (muo *MemberUpdateOne) SetNillableDescription(s *string) *MemberUpdateOne {
	if s != nil {
		muo.SetDescription(*s)
	}
	return muo
}

// SetHeadacount sets the "headacount" field.
func (muo *MemberUpdateOne) SetHeadacount(i int8) *MemberUpdateOne {
	muo.mutation.ResetHeadacount()
	muo.mutation.SetHeadacount(i)
	return muo
}

// SetNillableHeadacount sets the "headacount" field if the given value is not nil.
func (muo *MemberUpdateOne) SetNillableHeadacount(i *int8) *MemberUpdateOne {
	if i != nil {
		muo.SetHeadacount(*i)
	}
	return muo
}

// AddHeadacount adds i to the "headacount" field.
func (muo *MemberUpdateOne) AddHeadacount(i int8) *MemberUpdateOne {
	muo.mutation.AddHeadacount(i)
	return muo
}

// Mutation returns the MemberMutation object of the builder.
func (muo *MemberUpdateOne) Mutation() *MemberMutation {
	return muo.mutation
}

// Where appends a list predicates to the MemberUpdate builder.
func (muo *MemberUpdateOne) Where(ps ...predicate.Member) *MemberUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MemberUpdateOne) Select(field string, fields ...string) *MemberUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Member entity.
func (muo *MemberUpdateOne) Save(ctx context.Context) (*Member, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MemberUpdateOne) SaveX(ctx context.Context) *Member {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MemberUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MemberUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MemberUpdateOne) check() error {
	if v, ok := muo.mutation.MemberID(); ok {
		if err := member.MemberIDValidator(v); err != nil {
			return &ValidationError{Name: "member_id", err: fmt.Errorf(`ent: validator failed for field "Member.member_id": %w`, err)}
		}
	}
	return nil
}

func (muo *MemberUpdateOne) sqlSave(ctx context.Context) (_node *Member, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(member.Table, member.Columns, sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Member.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, member.FieldID)
		for _, f := range fields {
			if !member.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != member.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.MemberID(); ok {
		_spec.SetField(member.FieldMemberID, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.AddedMemberID(); ok {
		_spec.AddField(member.FieldMemberID, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.Name(); ok {
		_spec.SetField(member.FieldName, field.TypeString, value)
	}
	if value, ok := muo.mutation.Description(); ok {
		_spec.SetField(member.FieldDescription, field.TypeString, value)
	}
	if value, ok := muo.mutation.Headacount(); ok {
		_spec.SetField(member.FieldHeadacount, field.TypeInt8, value)
	}
	if value, ok := muo.mutation.AddedHeadacount(); ok {
		_spec.AddField(member.FieldHeadacount, field.TypeInt8, value)
	}
	_node = &Member{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
