// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend_golang/ent/member"
	"backend_golang/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescMemberID is the schema descriptor for member_id field.
	memberDescMemberID := memberFields[0].Descriptor()
	// member.MemberIDValidator is a validator for the "member_id" field. It is called by the builders before save.
	member.MemberIDValidator = memberDescMemberID.Validators[0].(func(int64) error)
}
