// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend_golang/ent/announcement"
	"backend_golang/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	announcementFields := schema.Announcement{}.Fields()
	_ = announcementFields
	// announcementDescTitle is the schema descriptor for title field.
	announcementDescTitle := announcementFields[0].Descriptor()
	// announcement.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	announcement.TitleValidator = announcementDescTitle.Validators[0].(func(string) error)
	// announcementDescContent is the schema descriptor for content field.
	announcementDescContent := announcementFields[1].Descriptor()
	// announcement.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	announcement.ContentValidator = announcementDescContent.Validators[0].(func(string) error)
}
