// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend_golang/ent/predicate"
	"backend_golang/ent/transientmember"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TransientMemberDelete is the builder for deleting a TransientMember entity.
type TransientMemberDelete struct {
	config
	hooks    []Hook
	mutation *TransientMemberMutation
}

// Where appends a list predicates to the TransientMemberDelete builder.
func (tmd *TransientMemberDelete) Where(ps ...predicate.TransientMember) *TransientMemberDelete {
	tmd.mutation.Where(ps...)
	return tmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tmd *TransientMemberDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tmd.sqlExec, tmd.mutation, tmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tmd *TransientMemberDelete) ExecX(ctx context.Context) int {
	n, err := tmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tmd *TransientMemberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(transientmember.Table, sqlgraph.NewFieldSpec(transientmember.FieldID, field.TypeInt))
	if ps := tmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tmd.mutation.done = true
	return affected, err
}

// TransientMemberDeleteOne is the builder for deleting a single TransientMember entity.
type TransientMemberDeleteOne struct {
	tmd *TransientMemberDelete
}

// Where appends a list predicates to the TransientMemberDelete builder.
func (tmdo *TransientMemberDeleteOne) Where(ps ...predicate.TransientMember) *TransientMemberDeleteOne {
	tmdo.tmd.mutation.Where(ps...)
	return tmdo
}

// Exec executes the deletion query.
func (tmdo *TransientMemberDeleteOne) Exec(ctx context.Context) error {
	n, err := tmdo.tmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{transientmember.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tmdo *TransientMemberDeleteOne) ExecX(ctx context.Context) {
	if err := tmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
